---
networks:
  safezone:
    driver: local
services:
  #  api:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    depends_on:
  #      - database
  #    networks:
  #      - safezone
  #    links:
  #      - database
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  postgres:
    container_name: postgres_safezone
    environment:
      - POSTGRES_DB=safezone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: "postgres:11.3"
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
volumes:
  redis_data:
    driver: local
version: "3"
