spring:
  application:
    name: safezone
  datasource:
    url: jdbc:postgresql://localhost:5432/safezone
    username: postgres
    password: postgres
    driverName: postgresql
  debug:
    port: 9990
  server:
    port: 8080
    contextPath: /safezone